name: Next.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Run Next.js tests (if present)
        run: |
          if [ -f package.json ] && grep -q 'test' package.json; then
            npm test
          else
            echo "No test script found."
          fi
      - name: Start Next.js app (for preview, optional)
        run: npm run start
        if: ${{ always() }}
        continue-on-error: true
